name: blog
volumes:
  node-modules:

services:
  frontend:
    build:
      context: ../
      target: development
    ports:
      - "5173:5173"
    volumes:
      - ..:/usr/src/app
      - node-modules:/usr/src/app/node_modules
    environment:
      NODE_ENV: development
    command: sleep infinity
